
namePrefix: dev-

commonLabels:
  env: dev

patchesStrategicMerge:
- replica-count.yml

namespace: dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: phathdt379/express-todo
  newTag: dev-d7996f4
