apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

commonLabels:
  env: prod

patchesStrategicMerge:
- replica-count.yml

namespace: prod

images:
- name: phathdt379/express-todo
  newTag: prod-544887c
