apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-demo
    env: dev
  name: dev-nginx-demo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
      env: dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-demo
        env: dev
    spec:
      containers:
      - image: phathdt379/express-todo:dev-7c6f425d6913da73a33605bcc4d37ee38786aeaf
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 5
        name: nginx-demo
        ports:
        - containerPort: 80
          name: nginx-demo
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
